name: Sync multiple branches

on:
    workflow_run:
        workflows: ['Changelog']
        types:
            - completed

jobs:
    merge-main-to-develop:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Merge main to develop
              run: |
                  git checkout develop
                  git merge origin/main
                  git push origin develop
