name: Sync multiple branches

on:
    workflow_run:
        workflows: ['Changelog']
        types:
            - completed

jobs:
    sync-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Merge main -> develop
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  from_branch: main
                  target_branch: develop
                  github_token: ${{ secrets.GITHUB_TOKEN }}
